# All size units are in GB

- benchmark:
    API: "mpi" # One of hdf5, posix or mpio
    shape: [1000,1000,1000]
    path: "dataDir/mpi"
    isCollective: true
- benchmark:
    API: "posix" # One of hdf5, posix or mpio
    filePerProcess: true # If false all processes will write to a single shared file
    shape: [10000000,1,1]
    path: "dataDir/posix"
- benchmark:
    name: "posix-sharedFile"
    API: "posix" # One of hdf5, posix or mpio
    filePerProcess: false # If false all processes will write to a single shared file
    shape: [1000000000,1,1]
    path: "dataDir/posix-sharedFile"
- benchmark:
    API: "hdf5" # One of hdf5, posix or mpio
    filePerProcess: false # If false all processes will write to a single shared file
    shape: [1000,1000,1000]
    path: "dataDir/hdf5"

    