# All size units are in GB

benchmark:
  API: "posix" # One of hdf5, posix or mpio
  filePerProcess: false # If false all processes will write to a single shared file
  shape: [100000000,1,1]
  path: "dataDir"